version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "DepUpdate"
      include: "scope"
